spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: JC-Admin
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JustChat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: 123456
server:
  port: 8084
Raven:
  key: 爱你老妈
logging:
  level:
    www.raven.jc.feign.*: DEBUG