dubbo:
  protocol:
    name: dubbo
  registry:
    address: nacos://10.21.32.154:8848
    group: dubbo
    parameters:
      namespace: d7a1b125-8d08-47f5-bb6c-2020abe9f6f8
spring:
  data:
    mongodb:
      uri: mongodb://10.21.32.192:27017/jc
      auto-index-creation: true
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  cache:
    type: redis
    #指定存活时间（ms）
    redis.time-to-live: 10800000
    #是否缓存空值，可以防止缓存穿透
    redis.cache-null-values: true
  application:
    name: JC-Chat
  cloud:
    stream:
      function:
        definition: eventUserToIm;eventFeedToIm;eventImToIm;
      rocketmq:
        bindings:
          eventFeedToIm-in-0:
            consumer:
              messageModel: BROADCASTING
          eventUserToIm-in-0:
            consumer:
              messageModel: BROADCASTING
          eventImToIm-in-0:
            consumer:
              messageModel: BROADCASTING
          producer-out-1:
            producer:
              sync: false
              group: output-1
          producer-out-0:
            producer:
              sync: false
              group: output-0
        binder:
          name-server: 10.21.32.221:9876
      bindings:
          producer-out-1:
           destination: eventImToIm
          producer-out-0:
           destination: eventImToIm
          eventUserToIm-in-0:
            consumer:
              max-attempts: 3
            destination: eventUserToIm
            group: im-module
          eventFeedToIm-in-0:
            consumer:
              max-attempts: 3
            destination: eventFeedToIm
            group: im-module
          eventImToIm-in-0:
            consumer:
              max-attempts: 3
            destination: eventImToIm
            group: im-module
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JC_chat?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 8081
jwt:
  key: 爱你老妈
  expire: 604800000
logging:
  level:
    www.raven.jc.api.*: DEBUG