spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: JC-File
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
server:
  port: 8888
minio:
    endpoint: http://10.21.32.192:9000
    accessKey: admin
    secretKey: admin123456
    bucket: raven
jwt:
  key: 爱你老妈
  expire: 604800000