dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://10.21.32.154:8848
    group: dubbo
    parameters:
      namespace: d7a1b125-8d08-47f5-bb6c-2020abe9f6f8
  application:
    qos-host: localhost
    qos-port: 8091
spring:
  threads:
    virtual:
      enabled: true
  web:
    resources:
      add-mappings: false
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  application:
    name: JC-User
  cloud:
    stream:
      bindings:
        producer-out-1:
          destination: eventUserToIm
        producer-out-0:
          destination: eventUserToIm
      rocketmq:
        bindings:
          producer-out-1:
            producer:
              sync: false
              group: output-1
          producer-out-0:
            producer:
              sync: false
              group: output-0
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:postgresql://10.21.32.192:5432/postgres
    username: postgres
    password: 123456
server:
  port: 8080
jwt:
  key: 爱你老妈
  expire: 604800000
