dubbo:
  protocol:
    name: dubbo
  registry:
    address: nacos://10.21.32.154:8848
    group: dubbo
    parameters:
      namespace: d7a1b125-8d08-47f5-bb6c-2020abe9f6f8
spring:
  #  threads:
  #    virtual:
  #      enabled: true
  datasource:
    url: jdbc:postgresql://10.21.32.192:5432/postgres
    username: postgres
    password: 123456
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  cache:
    type: redis
    #指定存活时间（ms）
    redis.time-to-live: 86400000
    #是否缓存空值，可以防止缓存穿透
    redis.cache-null-values: true
  cloud:
    stream:
      bindings:
        producer-out-1:
          destination: eventFeedToIm
      rocketmq:
        bindings:
          producer-out-1:
            producer:
              sync: false
              group: output-1
          producer-out-0:
            producer:
              sync: false
              group: output-0
        binder:
          name-server: 10.21.32.221:9876
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  application:
    name: JC-Social
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
server:
  port: 8071
redis:
  sorted-set:
    max-size: 15
    expire-days: 3
jwt:
  key: 爱你老妈
  expire: 604800000