dubbo:
  registry:
    address: nacos://10.21.32.154:8848
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  application:
    name: JC-Auth
  cloud:
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JustChat?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: root
server:
  port: 8082
Raven:
  key: 爱你老妈
logging:
  level:
    www.raven.jc.api.*: DEBUG
