spring:
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  application:
    name: JC-Chat
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: broadcast
      rocketmq:
        bindings:
          producer-out-0:
            producer:
              group: output_1
        binder:
          name-server: 10.21.32.154

    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JustChat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: 123456
server:
  port: 8081
Raven:
  key: 爱你老妈