dubbo:
  protocol:
    name: dubbo
  registry:
    address: nacos://10.21.32.154:8848
spring:
  data:
    mongodb:
      uri: mongodb://10.21.32.192:27017/jc
      auto-index-creation: true
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  application:
    name: JC-Chat
  cloud:
    stream:
      bindings:
        producer-out-1:
          destination: eventChatToUser
        producer-out-0:
          destination: eventChatToUser
      rocketmq:
        bindings:
          producer-out-1:
            producer:
              group: output-1
          producer-out-0:
            producer:
              group: output-0
        binder:
          name-server: 10.21.32.221:9876
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JC_chat?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 8081
Raven:
  key: 爱你老妈
logging:
    level:
      www.raven.jc.api.*: DEBUG