dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://10.21.32.154:8848
    group: dubbo
    parameters:
      namespace: d7a1b125-8d08-47f5-bb6c-2020abe9f6f8

  application:
    qos-host: localhost
    qos-port: 8091
spring:
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  application:
    name: JC-User
  cloud:
    stream:
      function:
        definition: eventChatToUser;eventSocialToUser;
      rocketmq:
        binder:
          name-server: 10.21.32.221:9876
        bindings:
          eventSocialToUser-in-0:
            consumer:
              messageModel: BROADCASTING
          eventChatToUser-in-0:
            consumer:
              messageModel: BROADCASTING
      bindings:
        eventChatToUser-in-0:
          consumer:
            max-attempts: 3
          destination: eventChatToUser
          group: user-module
        eventSocialToUser-in-0:
            consumer:
              max-attempts: 3
            destination: eventSocialToUser
            group: user-module
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JC_user?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
server:
  port: 8080
Raven:
  key: 爱你老妈
