spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: JC-User
  cloud:
    stream:
      function:
        definition: eventUserSendMsg;eventUserJoinRoomApply
      rocketmq:
        binder:
          name-server: 10.21.32.221:9876
        bindings:
          eventUserJoinRoomApply-in-0:
            consumer:
              messageModel: BROADCASTING
          eventUserSendMsg-in-0:
            consumer:
              messageModel: BROADCASTING
      bindings:
        eventUserJoinRoomApply-in-0:
          destination: eventRoomApply
          group: user-module-room-apply
        eventUserSendMsg-in-0:
          destination: eventUserSendMsg
          group: user-module-user-msg
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JC_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: 123456
server:
  port: 8080
Raven:
  key: 爱你老妈
Ipfs:
  api: /ip4/127.0.0.1/tcp/5001
