spring:
  redis:
    address: redis://10.21.32.221:6379
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  application:
    name: JC-User
  cloud:
    stream:
      function:
        definition: eventChatToUser;
      rocketmq:
        binder:
          name-server: 10.21.32.221:9876
        bindings:
          eventChatToUser-in-0:
            consumer:
              messageModel: BROADCASTING
      bindings:
        eventChatToUser-in-0:
          consumer:
            max-attempts: 3
          destination: eventChatToUser
          group: user-module
    nacos:
      discovery:
        server-addr: 10.21.32.154:8848
  datasource:
    url: jdbc:mysql://10.21.32.154:3306/JC_user?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: user
    password: 123456
server:
  port: 8080
Raven:
  key: 爱你老妈
Ipfs:
  api: /ip4/127.0.0.1/tcp/5001
logging:
  level:
    www.raven.jc.api.*: DEBUG